/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package userinterface.Pharmacy;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.OrganizationDirectory;
import Business.Organization.PharmacyOrganization;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author aniketmirajkar
 */
public class PharmacistWorkArea extends javax.swing.JPanel {

    /** Creates new form PharmacistWorkArea */
    
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    private PharmacyOrganization pharmacyOrganization;
    private OrganizationDirectory directory;
    Enterprise enterprise;
    Person person;
    private UserAccount userAccount;
    PersonDirectory personDirectory;
    
    public PharmacistWorkArea(JPanel userProcessContainer, UserAccount account, PharmacyOrganization pharmacyOrganization, Enterprise enterprise ,EcoSystem ecosystem, PersonDirectory personDirectory) {
        initComponents();
        
        this.userProcessContainer=userProcessContainer;   
        this.userAccount = account;
        this.enterprise = enterprise;
        this.ecosystem=ecosystem;
        this.pharmacyOrganization = (PharmacyOrganization)pharmacyOrganization;
        this.enterprise = enterprise;
        this.personDirectory = personDirectory;
        this.userAccount = account;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
